<testsuite name="Mocha Tests" tests="9" failures="0" errors="1" skipped="3" timestamp="Tue, 26 Feb 2019 06:25:45 GMT" time="0.017">
<testcase classname="Puppeteer - Example.com" name="Go to page, take screenshot, and compare with expected" time="0.001"/>
<testcase classname="Test async add function" name="2 + 2 is 4" time="0.002"><failure>expected 4 to equal 5

      + expected - actual

      -4
      +5

AssertionError: expected 4 to equal 5
    at Context.it (test/test_add_async.js:12:22)</failure></testcase>
<testcase classname="Test async add function" name="3 + 3 is 6" time="0"/>
<testcase classname="Mocha with Chai Assertion styles" name="Chai.assert" time="0.001"/>
<testcase classname="Mocha with Chai Assertion styles" name="Chai.expect" time="0.001"/>
<testcase classname="Mocha with Chai Assertion styles" name="Chai.should" time="0"/>
<testcase classname="Is Mocha alive? Check with an Array #indexOf()" name="should return -1 when the value is not present" time="0"><skipped/></testcase>
<testcase classname="Is Mocha alive? Check with an Array #indexOf() - copy" name="should return -1 when the value is not present" time="0"><skipped/></testcase>
<testcase classname="Is Mocha alive? Check with an Array #indexOf() - copy" name="should return -1 when the value is not present" time="0"><skipped/></testcase>
</testsuite>
